"use client";

import { useRef, useState, useEffect } from "react";
import { Eye, Printer, Loader2 } from "lucide-react";
import { Button } from "@/components/ui/button";

interface ReportViewerProps {
  html: string;
}

export function ReportViewer({ html }: ReportViewerProps) {
  const iframeRef = useRef<HTMLIFrameElement>(null);
  const [loading, setLoading] = useState(true);
  const [iframeHeight, setIframeHeight] = useState("90vh");

  useEffect(() => {
    const iframe = iframeRef.current;
    if (!iframe) return;

    const handleLoad = () => {
      setLoading(false);
      // Auto-resize iframe to content height
      try {
        const doc = iframe.contentDocument;
        if (doc?.body) {
          const height = doc.body.scrollHeight + 40;
          setIframeHeight(`${height}px`);
        }
      } catch {
        // cross-origin issues - fall back to default height
      }
    };

    iframe.addEventListener("load", handleLoad);
    return () => iframe.removeEventListener("load", handleLoad);
  }, [html]);

  function handlePrint() {
    const iframe = iframeRef.current;
    if (iframe?.contentWindow) {
      iframe.contentWindow.print();
    }
  }

  return (
    <div className="min-h-screen bg-gray-100">
      {/* Header bar */}
      <div className="sticky top-0 z-10 border-b bg-white shadow-sm">
        <div className="mx-auto flex max-w-5xl items-center justify-between px-4 py-3">
          <div className="flex items-center gap-2">
            <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#0D7377]">
              <Eye className="h-4 w-4 text-white" />
            </div>
            <div>
              <div className="text-sm font-bold tracking-wider text-[#0D7377]">
                SEHRA
              </div>
              <div className="text-[9px] tracking-widest text-muted-foreground uppercase">
                Shared Report
              </div>
            </div>
          </div>
          <Button
            variant="outline"
            size="sm"
            onClick={handlePrint}
            className="gap-1.5"
          >
            <Printer className="h-3.5 w-3.5" />
            Print
          </Button>
        </div>
      </div>

      {/* Report content */}
      <div className="mx-auto max-w-5xl py-6 px-4">
        {loading && (
          <div className="flex items-center justify-center py-20">
            <Loader2 className="h-6 w-6 animate-spin text-[#0D7377]" />
            <span className="ml-2 text-sm text-muted-foreground">
              Loading report...
            </span>
          </div>
        )}
        <iframe
          ref={iframeRef}
          srcDoc={html}
          className={`w-full rounded-lg border bg-white shadow-lg ${loading ? "invisible h-0" : ""}`}
          style={{ minHeight: loading ? 0 : iframeHeight }}
          sandbox="allow-scripts allow-same-origin"
          title="SEHRA Report"
        />
      </div>

      {/* Footer */}
      <div className="border-t bg-white py-4 text-center text-xs text-muted-foreground">
        Generated by SEHRA Analysis Platform
      </div>
    </div>
  );
}
